# Generated by Django 6.0.6 on 2026-06-11 19:27

import django.core.validators
import django.db.models.deletion
import trojan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('TOP_COURSE', 'top course'), ('LIKED_COURSE', 'liked course'), ('L_COURSE', 'L course'), ('TRASH_COURSE', 'trash course')], help_text='A badge awarded to a course, depending on its standing among the student body.')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('IB', 'International Baccalaureate'), ('AP', 'Advanced Placement'), ('S', 'Sports'), ('SHSM', 'Specialist High Skills Major'), ('FI', 'French Immersion'), ('EF', 'Extended French'), ('CM', 'Core/Mainstream')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('TOP_TEACHER', 'top teacher'), ('W_TEACHER', 'W teacher'), ('L_TEACHER', 'L teacher'), ('BOTTOM_TEACHER', 'bottom teacher')], help_text='A badge awarded to a teacher, depending on their standing among the student body.')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, help_text='A human-generated summary of a teacher.')),
                ('generated_summary', models.CharField(blank=True, default=models.CharField(blank=True, help_text='A human-generated summary of a teacher.'), help_text='A summary of a teacher generated using AI, based on the review text.')),
                ('name', models.CharField()),
                ('code', models.CharField(unique=True)),
                ('description', models.CharField()),
                ('badge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='trojan.coursebadge')),
                ('program', models.ForeignKey(help_text='Whether this course belongs to a specific program at the school.', on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='trojan.program')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=trojan.models.course_directory_path)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='trojan.course')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('district', models.CharField()),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('province_code', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=64)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('programs', models.ManyToManyField(help_text='The programs offered at this school.', related_name='schools', to='trojan.program')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculties', to='trojan.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.PositiveIntegerField(unique=True)),
                ('grade', models.PositiveIntegerField()),
                ('program', models.ManyToManyField(related_name='students', to='trojan.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='trojan.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='trojan.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='trojan.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, help_text='A human-generated summary of a teacher.')),
                ('generated_summary', models.CharField(blank=True, default=models.CharField(blank=True, help_text='A human-generated summary of a teacher.'), help_text='A summary of a teacher generated using AI, based on the review text.')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-Binary'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=2)),
                ('pronouns', models.CharField(blank=True, choices=[('he_him', 'He/Him'), ('she_her', 'She/Her'), ('they_them', 'They/Them'), ('other', 'Other/Ask')])),
                ('date_of_birth', models.DateField()),
                ('pdsb_number', models.CharField(max_length=20, unique=True)),
                ('pdsb_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('pdsb_direct_email', models.EmailField(blank=True, help_text='The email that teachers check much more frequently than their regular one', max_length=254, unique=True)),
                ('personal_email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('school_phone_extension', models.PositiveIntegerField()),
                ('personal_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('room_number', models.CharField(blank=True, max_length=10)),
                ('home_address', models.TextField(blank=True)),
                ('business_address', models.TextField(blank=True)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('sunshine_list', models.URLField(blank=True, help_text='The website containing teacher details for those who make over $100k. Fun Fact: Initially created to manufacture backlash against teacher to cut their funding.', unique=True)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('reddit', models.URLField(blank=True)),
                ('snapchat', models.CharField(blank=True)),
                ('discord', models.CharField(blank=True)),
                ('courses', models.ManyToManyField(related_name='teachers', to='trojan.course')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teachers', to='trojan.school')),
                ('badge', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='trojan.teacherbadge')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherPictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=trojan.models.teacher_directory_path)),
                ('is_profile_picture', models.BooleanField(default=False, help_text='Allows selection of profile picture from all the pictures.')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='trojan.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='CourseReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trojan.course')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_reviews', to='trojan.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'course'), name='unique_course_student_review')],
            },
        ),
        migrations.CreateModel(
            name='TeacherReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('text', models.TextField()),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_reviews', to='trojan.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='trojan.teacher')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'teacher'), name='unique_teacher_student_review')],
            },
        ),
    ]
