# Generated by Django 6.0.6 on 2026-06-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan', '0002_alter_teacher_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='generated_summary',
            field=models.CharField(blank=True, default=None, help_text='A summary of a teacher generated using AI, based on the review text.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pdsb_number',
            field=models.CharField(help_text="This 'number' begins with a 'p', and is used to identify teachers in Peel. You must include the 'p', when registering the teacher.", max_length=20, unique=True, verbose_name='PDSB Number'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='school_phone_extension',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
